### ISSUE TITLE
Not clear how to point drake_bazel_external at a release

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake-external-examples#161]
The `drake_bazel_external/WORKSPACE` file indicates how to pin to a specific drake commit, or to live on master, but not how to pin to a numbered release.  The naive approach of putting the release tag name into `DRAKE_COMMIT` does not work.

**Comment by jwnimmer-tri** [comment]
I'd guess that `COMMIT = "v0.15.0"` would download successfully -- the https://github.com/RobotLocomotion/drake/releases/tag/v0.15.0 links to https://github.com/RobotLocomotion/drake/archive/v0.15.0.tar.gz as its canonical answerl.

However, when using a v-numbered release, the `strip_prefix` argument needs to lose the leading `v` since the to-level folder name in the source archive uses the bare version number, without the `v`.

**Comment by ggould-tri** [comment]
Yes, I believe that the strip_prefix bit is the problem.  Should be an easy enough fix, I just scribed the bug as I was working through it -- a naive Drake user will need a bit of guidance.
