### ISSUE TITLE
[drake_ament_cmake_installed] Broken link in README

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake-external-examples#310]
In the drake_ament_cmake_installed [README](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_ament_cmake_installed#readme), the `ament_cmake` [link](https://github.com/RobotLocomotion/drake-external-examples/blob/70a3831a18c3fe7e4bffcae1ef785a97629b583e/drake_ament_cmake_installed/README.md?plain=1#L3) is broken.

**Comment by ahcorde** [comment]
The right link is https://docs.ros.org/en/rolling/How-To-Guides/Ament-CMake-Documentation.html

you might want to change the ROS distro branch

**Comment by jwnimmer-tri** [comment]
Great, thanks!

Since the example is hard-coded to Humble, let's use this link:
- https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Documentation.html

When we upgrade from Humble to something newer, we can change the docs and setup scripts at the same time.

+@BetsyMcPhail could you or @nicolecheetham please open a PR for this?

**Comment by jwnimmer-tri** [comment]
Fixed in #337.
